name: Frontend Chat CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
            
jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: node
           
  cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        
      - name: Docker login 
        run: docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}
          
      - name: Build
        run: docker build --no-cache --progress=plain -t front .
          
      - name: Tags
        run: |
             docker tag front ${{ secrets.USERNAME }}/front:${{ github.sha }}
             docker tag front ${{ secrets.USERNAME }}/front:latest
             
      - name: Push
        run: |
            docker push ${{ secrets.USERNAME }}/front:${{ github.sha }}
            docker push ${{ secrets.USERNAME }}/front:latest
